pub mod call_hierarchy;
pub mod code_actions;
pub mod definition;
pub mod diagnostics;
pub mod diagnostics_cache;
pub mod doc_index;
pub mod dsl;
pub mod edit;
pub mod edit_apply;
pub mod edit_extract;
pub mod edit_pending;
pub mod edit_range_apply;
pub mod edit_types;
pub mod exec_helpers;
pub mod execute;
pub mod execute_edit_ops;
mod execute_lsp;
pub mod formatting;
pub mod grep;
pub mod hover;
pub mod impls;
pub mod indent;
pub mod json_util;
pub mod language_specific;
pub mod list_dir;
pub mod operation;
pub mod process_ops;
pub mod read_file;
pub mod references;
pub mod rename;
pub mod serde_helpers;
pub mod symbol_cache;
mod symbol_cache_persist;
mod symbol_cache_seed;
pub mod symbol_info;
pub mod symbol_list;
pub mod symbol_match;
pub mod symbol_parent_child;
pub mod symbol_search;
pub mod symbol_search_cmd;
pub mod symbol_walk;
pub mod task_ops;
pub mod workspace;

pub use execute::execute_batch;
pub use operation::{Operation, OperationResult};

// Re-export the canonical source extension list from detect_lang.
pub use crate::lsp::detect_lang::SOURCE_EXTS;
